#!/bin/bash
docker pull ghcr.io/mrc-ide/orderly.runner:main
docker run --rm \
       -v montagu_orderly_library:/library \
       -v $PWD/packages:/packages:ro \
       -w /packages \
       ghcr.io/mrc-ide/orderly.runner:main ./install_packages
