#!/usr/bin/env bash
set -eu
export VAULT_ADDR=https://vault.dide.ic.ac.uk:8200
export VAULT_TOKEN=$(vault login -method=github -token-only)
NAME=$1

# We will replace this with a simple container that has has python and
# hvac installed I think, which pulls keys and writes them all
# out. For now, this will by easy to iterate with though.

docker volume create privateer_keys > /dev/null
docker run --env=VAULT_TOKEN --env=VAULT_ADDR -it \
       --entrypoint=sh \
       -v privateer_keys:/keys \
       "hashicorp/vault" \
       -c "rm -f /keys/known_hosts /keys/id_rsa /keys/id_rsa.pub &&
vault read -field=private /secret/vimc/privateer/keys/$NAME > /keys/id_rsa &&
vault read -field=public /secret/vimc/privateer/keys/$NAME > /keys/id_rsa.pub &&
echo annex2.montagu.dide.ic.ac.uk $(vault read -field=public /secret/vimc/privateer/keys/annex) > /keys/known_hosts
echo 146.179.177.21 $(vault read -field=public /secret/vimc/privateer/keys/annex) > /keys/known_hosts"
